In [1]:
import numpy as np
print(np.__version__)

1.26.4


In [3]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

first parameter is just matrix dimention and second one the value in it simply 
use print(np.info(np.full)) to view full describtion

In [5]:
np.full((3,3), True)

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [6]:
arr = np.arange(10)
arr[arr % 2 == 1]

array([1, 3, 5, 7, 9])

In [7]:
arr = np.arange(10)
arr[arr % 2 == 1] = -1
print(arr)

[ 0 -1  2 -1  4 -1  6 -1  8 -1]


In [8]:
#copy function usage to make changes in the array
arr = np.arange(10)
out = arr.copy()
out[out % 2 == 1] = 0
print('Modified Array')
print(out)
print('Original Array')
print(arr)

Modified Array
[0 0 2 0 4 0 6 0 8 0]
Original Array
[0 1 2 3 4 5 6 7 8 9]


In [11]:
#reshape concept
arr = np.arange(10)
arr.reshape(2, 5)
print(arr)

#second one automatically would be decided properly if -1
arr.reshape(2, -1)
print(arr)

[0 1 2 3 4 5 6 7 8 9]
[0 1 2 3 4 5 6 7 8 9]


In [16]:
#stack two array vertically
#arrays here is work in referrenced manner
a = np.arange(10).reshape(2, -1)
b = np.repeat(1, 10).reshape(2, 5)
np.vstack([a,b])

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [17]:
#horizontal stacking
np.hstack([a,b])

array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

In [18]:
#for axis 0, concatenation np.r_ used 
a = np.array([1,2,3])
np.r_[np.repeat(a,3), np.tile(a, 3)]
#repeat just repeats, and tile is simply repeat the arrays like a titled manner

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])

In [23]:
#intersection of two arrays
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
np.intersect1d(a, b)

array([2, 4])

In [21]:
#setdifference in numpy
np.setdiff1d(a, b)


array([3, 5, 6])

In [25]:
#get the positions where elements of two arrays perfectly matches
#both array size of dimension should be same to perform this operation
np.where(a == b)

(array([1, 3, 5, 7], dtype=int64),)

In [26]:
#extract specified numbers in a range of array values
a = np.array([2, 3, 4, 5, 6, 7,  8, 9, 10, 13])
a[(a >= 5) & (a <= 10)]


array([ 5,  6,  7,  8,  9, 10])

In [28]:
#reverse rows of a 2d array 
arr = np.arange(9).reshape(3,3)
print(arr)
print(arr[::-1, :])
#reverse columns of a 2d array
arr = np.arange(9).reshape(3,3)
print(arr)
print(arr[:, ::-1])

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[6 7 8]
 [3 4 5]
 [0 1 2]]
[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[2 1 0]
 [5 4 3]
 [8 7 6]]


In [31]:
rand_arr = np.random.uniform(5, 10, size=(5,3))
rand_arr

array([[6.92393235, 9.71355047, 7.49169957],
       [5.07713145, 6.31167535, 7.21526276],
       [6.79288434, 8.6487118 , 8.08956384],
       [5.62536545, 6.00995898, 6.96314815],
       [9.1222164 , 6.70796787, 9.48598311]])